version: '3.8'

services:
  icecast:
    image: libretime/icecast:2.4.4-debian
    volumes:
      #- ./icecast.xml:/etc/icecast.xml
      - logs:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ICECAST_PASSWORD=123@mudar
      - ICECAST_RELAY_PASSWORD=123@mudar
      - ICECAST_SOURCE_PASSWORD=123@mudar
      - ICECAST_ADMIN_PASSWORD=123@mudar
      - ICECAST_ADMIN_USERNAME=admin
      - ICECAST_ADMIN_EMAIL=teste@admin.com
      - ICECAST_LOCATION=America/Sao_Paulo
      - ICECAST_HOSTNAME=localhost
      - ICECAST_MAX_CLIENTS=100
      - ICECAST_MAX_SOURCES=100
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nginx

  nginx:
    image: nginx:latest
    depends_on:
      - icecast
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/icecast:/etc/ssl/icecast:ro
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nginx

volumes:
  logs:
    external: true
    name: icecast-logs

networks:
  nginx:
    external: true
    name: nginx
