name: Container

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.4.4"
          - "2.5-beta3"

    env:
      LATEST: "2.4.4"
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/${{ github.repository_owner }}/icecast

    if: ${{ github.repository_owner == 'jooola' }}
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: make icecast-${{ matrix.version }}.tar.gz

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ matrix.version }},suffix=-{{date 'YYYYMMDD'}}
            type=raw,value=${{ matrix.version }}
            type=raw,value=latest,enable=${{ matrix.version == env.LATEST }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
